http:
  host: 'localhost'
  port: 3200

db:
  type: 'mysql'
  host: 'localhost'
  port: 3307
  username: 'root'
  password: '12345678'
  database: 'test'
  autoLoadEntities: true
  synchronize: true

jwt:
  secret: NymS8iF33VEhVrFUX3s67N5sVFqcrf6J
  signOptions:
    expiresIn: '3d'
