http:
  host: 'localhost'
  port: 3100

db:
  type: 'mysql'
  host: 'localhost'
  port: 3307
  username: 'root'
  password: '12345678'
  database: 'test'
  autoLoadEntities: true
  synchronize: true

jwt:
  token:
    secret: NymS8iF33VEhVrFUX3s67N5sVFqcrf6J
    signOptions:
      expiresIn: '3h'
  refreshToken:
    secret: NymS8iF33VEhVrFUX3s67N5sVFqcrf6J
    expiresIn: '3d'

bcrypt:
  saltOrRounds: 10

throttler:
  ttl: 60000
  limit: 10
